CREATE DATABASE IF NOT EXISTS kangwifi;
USE kangwifi;

CREATE TABLE pelanggan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100),
  nomor_wa VARCHAR(20),
  status ENUM('SUDAH BAYAR','BELUM BAYAR') DEFAULT 'BELUM BAYAR',
  tagihan INT DEFAULT 0
);

CREATE TABLE log_pengiriman (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pelanggan_id INT,
  pesan TEXT,
  response TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
